print("Введите первое число")
num1 = float(input())
print("Введите второе число")
num2 = float(input())
print("Сумма данных чисел:", num1+num2)
print("Разность данных чисел:", num1-num2)
print("Среднее арифметическое данных чисел:", (abs(num1) +abs(num2))/2)